### ISSUE TITLE
Wrong annotation keys

### ISSUE THREAD

**Issue by aecolley** [oracle/smith#17]
Smith makes `index.json` files with the obsolete annotation keys `org.opencontainers.ref.name` and `org.opencontainers.created`. Those keys were renamed before the final 1.0 release of the image spec (see opencontainers/image-spec@8ec42b74df4cc9dbb3f540a54126df259a3f7c0d).

This is a critical bug, because skopeo version 0.1.23 now expects the 1.0 image spec format, and it is current in the rhel7 extras repo.

**Comment by vishvananda** [comment]
thanks for pointing this out. I will fix it.
