### ISSUE TITLE
Hardcoded paths to ldconfig and chmod

### ISSUE THREAD

**Issue by jacob-carlborg** [oracle/smith#2]
I tried this tool on an Alpine based image that contains one fully statically linked executable that I would like to extract. The `smith.yaml` file looks like this:

```yaml
type: oci
package: remarkify.gz.tar
paths:
  - /usr/local/bin/remarkify
cmd:
  - /usr/local/bin/remarkify
```

When I run the tool I get this output:

```
INFO[0000] Building in /tmp/smith-build-443054379
INFO[0000] Installing package
INFO[0000] Installing package remarkify.gz.tar
WARN[0000] pigz binary not found, falling back to internal gzip
INFO[0004] Removing /tmp/smith-unpack-0
WARN[0010] chmod failed:
WARN[0010] Could not make paths readable: Error starting chmod -R go+rX /usr/local/bin/remarkify: fork/exec /usr/bin/chmod: no such file or directory
WARN[0010] ldconfig failed:
INFO[0010] Failed to install remarkify.gz.tar: Error starting ldconfig -v -N -X /: fork/exec /usr/sbin/ldconfig: no such file or directory
INFO[0010] Removing /tmp/smith-build-443054379
```

The executable is there:

```
# ls /tmp/smith-unpack-0/usr/local/bin/remarkify
/tmp/smith-unpack-0/usr/local/bin/remarkify
```

Doing the same thing but with a Debian based image gives the same result. I also tried with a Fedora based image, this works. To me it looks like it tries to find `/usr/bin/chmod` and `/usr/sbin/ldconfig` inside the unpacked image. These two paths don't exist in the Debian or Alpine based images. In those images these tools are located in `/bin/chmod` and `/sbin/ldconfig`.

I also tried the final example on [1], same issue.

[1] https://hackernoon.com/how-to-build-a-tiny-httpd-container-ae622c37db39

**Comment by vishvananda** [comment]
Thank you for reporting this. the command works for me so I'm thinking that it might be using your local PATH for lookup. Could you try working around this by setting your path appropriately before running smith? I will see if I can make it reset the path appropriately before doing the lookup.

**Comment by vishvananda** [comment]
Ok I believe i found the issue. It is actually looking for the binary on the host instead of the chroot. will make a fix

**Comment by vishvananda** [comment]
could you check to see if this pr resolves your issue? https://github.com/oracle/smith/pull/4

**Comment by vishvananda** [comment]
I went ahead and merged the fix. Please reopen if you are still seeing an issue.

**Comment by jacob-carlborg** [comment]
It works, thanks.
